channels:
  - conda-forge
  - set3mah

dependencies:
  - pyvista>=0.39
  - python-gmsh
  - meshio
  - pytest-cov
  - pytest
  - scipy
  - matplotlib
  - occt=7.7.0
  - cadquery=2.3.1
  - microgen
  - fedoo
  - simcoon